language: node_js
node_js:
  - "stable"
install:
  - npm install -g codecov
cache:
  directories:
  - node_modules
script:
  - npm test -- --coverage
  - npm run build
  - codecov
deploy:
  provider: pages
  skip_cleanup: true
  github_token: $GITHUB_TOKEN
  local_dir: build
  on:
    branch: master
