language: node_js
node_js:
  - "stable"
install:
  - npm install
  - npm install -g codecov
cache:
  directories:
  - node_modules
script:
  - npm test -- --coverage
  - codecov
  - npm run build
before_deploy: npm install now --no-save # Install Now CLI on Travis
deploy:
  - provider: script
    script: now --public --token $NOW_TOKEN
    skip_cleanup: true
    on:
      all_branches: true
      master: false
  - provider: script
    script: now --public --token $NOW_TOKEN && now alias
    skip_cleanup: true
    on:
      master: true

